# Build configuration for Evolution API add-on
# Uses Home Assistant community base images for each architecture

build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.7
  armv7: ghcr.io/hassio-addons/base:15.0.7
  amd64: ghcr.io/hassio-addons/base:15.0.7

# Build arguments passed to Dockerfile
args:
  EVOLUTION_VERSION: "2.3.7"
  NODE_VERSION: "20"

# Labels for the built image
labels:
  org.opencontainers.image.title: "Evolution API for Home Assistant"
  org.opencontainers.image.description: "WhatsApp API integration for Home Assistant"
  org.opencontainers.image.source: "https://github.com/bakeable/homeassistant-whatsapp-add-on"
  org.opencontainers.image.licenses: "Apache-2.0"
